name: publish

on:
  push:
    branches: [ master ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '15'
          check-latest: true
      - name: Build 🛠️
        run: |
          npm install
          cd demo
          npm install
          npx papua build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: demo
          FOLDER: demo/dist
          CLEAN: true
